"""remplace l index redondant par un index mesure utile

Revision ID: 92c3364b9519
Revises: d94729f4ef24
Create Date: 2026-08-24 10:28:00.334488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92c3364b9519'
down_revision: Union[str, Sequence[str], None] = 'd94729f4ef24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sensor_readings_equipment_time'))
        batch_op.create_index('ix_sensor_readings_sensor_value', ['sensor_name', 'value'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_readings', schema=None) as batch_op:
        batch_op.drop_index('ix_sensor_readings_sensor_value')
        batch_op.create_index(batch_op.f('ix_sensor_readings_equipment_time'), ['equipment_id', 'timestamp'], unique=False)

    # ### end Alembic commands ###
