"""schema initial : equipment, events, maintenance_history

Revision ID: 92d73464d6d3
Revises: 
Create Date: 2026-08-24 10:22:50.038802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92d73464d6d3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('equipment_id', sa.String(length=32), nullable=False),
    sa.Column('equipment_type', sa.String(length=64), nullable=False),
    sa.Column('site_id', sa.String(length=32), nullable=False),
    sa.Column('commissioning_date', sa.Date(), nullable=True),
    sa.Column('criticality', sa.String(length=16), nullable=False),
    sa.Column('manufacturer', sa.String(length=64), nullable=True),
    sa.Column('rated_power_kw', sa.Float(), nullable=True),
    sa.CheckConstraint("criticality IN ('low', 'medium', 'high', 'critical')", name='ck_equipment_criticality'),
    sa.CheckConstraint('rated_power_kw IS NULL OR rated_power_kw > 0', name='ck_equipment_power'),
    sa.PrimaryKeyConstraint('equipment_id')
    )
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipment_criticality'), ['criticality'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_equipment_type'), ['equipment_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_site_id'), ['site_id'], unique=False)

    op.create_table('events',
    sa.Column('event_id', sa.String(length=32), nullable=False),
    sa.Column('equipment_id', sa.String(length=32), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_type', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.CheckConstraint("event_type IN ('incident', 'intervention', 'observation', 'alert')", name='ck_events_type'),
    sa.CheckConstraint("severity IN ('low', 'medium', 'high', 'critical')", name='ck_events_severity'),
    sa.CheckConstraint('end_at IS NULL OR end_at >= start_at', name='ck_events_chronology'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.equipment_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('event_id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_events_equipment_start', ['equipment_id', 'start_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_severity'), ['severity'], unique=False)

    op.create_table('maintenance_history',
    sa.Column('maintenance_id', sa.String(length=32), nullable=False),
    sa.Column('event_id', sa.String(length=32), nullable=False),
    sa.Column('equipment_id', sa.String(length=32), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('intervention_type', sa.String(length=16), nullable=False),
    sa.Column('outcome', sa.String(length=24), nullable=False),
    sa.Column('downtime_minutes', sa.Integer(), nullable=False),
    sa.Column('labor_hours', sa.Float(), nullable=True),
    sa.Column('parts_cost_eur', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('parts_replaced_count', sa.Integer(), nullable=False),
    sa.Column('work_order_note', sa.Text(), nullable=True),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.CheckConstraint("intervention_type IN ('inspection', 'corrective', 'preventive', 'calibration', 'replacement')", name='ck_maintenance_type'),
    sa.CheckConstraint("outcome IN ('resolved', 'monitoring', 'parts_ordered', 'no_fault_found', 'follow_up_required')", name='ck_maintenance_outcome'),
    sa.CheckConstraint('closed_at IS NULL OR closed_at >= opened_at', name='ck_maintenance_chronology'),
    sa.CheckConstraint('downtime_minutes >= 0', name='ck_maintenance_downtime'),
    sa.CheckConstraint('parts_cost_eur IS NULL OR parts_cost_eur >= 0', name='ck_maintenance_cost'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.equipment_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('maintenance_id')
    )
    with op.batch_alter_table('maintenance_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_history_event_id'), ['event_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_history_event_id'))

    op.drop_table('maintenance_history')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_severity'))
        batch_op.drop_index(batch_op.f('ix_events_event_type'))
        batch_op.drop_index('ix_events_equipment_start')

    op.drop_table('events')
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipment_site_id'))
        batch_op.drop_index(batch_op.f('ix_equipment_equipment_type'))
        batch_op.drop_index(batch_op.f('ix_equipment_criticality'))

    op.drop_table('equipment')
    # ### end Alembic commands ###
