"""ajout de la table des mesures capteurs

Revision ID: d94729f4ef24
Revises: 92d73464d6d3
Create Date: 2026-08-24 10:25:02.378330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd94729f4ef24'
down_revision: Union[str, Sequence[str], None] = '92d73464d6d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_readings',
    sa.Column('reading_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipment_id', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sensor_name', sa.String(length=24), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.CheckConstraint("sensor_name IN ('vibration_mm_s', 'temperature_c', 'pressure_bar', 'current_a', 'rpm')", name='ck_sensor_readings_name'),
    sa.CheckConstraint('value IS NULL OR value >= 0', name='ck_sensor_readings_value'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.equipment_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('reading_id'),
    sa.UniqueConstraint('equipment_id', 'timestamp', 'sensor_name', name='uq_sensor_readings_logical_key')
    )
    with op.batch_alter_table('sensor_readings', schema=None) as batch_op:
        batch_op.create_index('ix_sensor_readings_equipment_time', ['equipment_id', 'timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_readings', schema=None) as batch_op:
        batch_op.drop_index('ix_sensor_readings_equipment_time')

    op.drop_table('sensor_readings')
    # ### end Alembic commands ###
